# Generated by Django 2.0.7 on 2018-11-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
