# Generated by Django 2.0.7 on 2018-11-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0002_delete_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseModel',
        ),
    ]
